# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\"\xbb\x01\n\x06MyData\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\r\n\x05\x66loat\x18\x02 \x01(\x02\x12\x0c\n\x04\x62ool\x18\x03 \x01(\x08\x12\x0e\n\x06string\x18\x04 \x01(\t\x12\x12\n\nlistNumber\x18\x05 \x03(\x05\x12\x12\n\nlistString\x18\x06 \x03(\t\x12\x1f\n\x04\x64ict\x18\x07 \x03(\x0b\x32\x11.MyData.DictEntry\x1a+\n\tDictEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MYDATA_DICTENTRY._options = None
  _MYDATA_DICTENTRY._serialized_options = b'8\001'
  _MYDATA._serialized_start=15
  _MYDATA._serialized_end=202
  _MYDATA_DICTENTRY._serialized_start=159
  _MYDATA_DICTENTRY._serialized_end=202
# @@protoc_insertion_point(module_scope)
